# Day 5 Groupby Practice

## 오늘 배울 것
- value_counts()
- groupby()
- sort_values()

## 오늘 목표
성별, 학년, 전공, 등급 같은 범주형 데이터를 기준으로 데이터를 집계하고 정렬하는 연습을 한다.

In [2]:
import pandas as pd
data = {
    "name" : ["timothy","james", "thomas", "paul","pedro", "maria",
              "john", "joseph", "David", "leon"],
    "gender" : ["m", "f", "m", "f", "m", "f", "m", "m", "f", "m"],
    "grade" : [1, 2, 3, 4, 1, 2, 3, 4, 1, 2],
    "major" : ["ee", "ee", "ee", "cs", "cs", "ds", "ee", "cs", "ds", "ee"],
    "score" : ["a", "c", "b", "f", "a", "b", "b", "c", "c", "c"],
    "study hour" : [6, 7, 2, 3, 4, 5, 2, 6, 7, 12]
}
df = pd.DataFrame(data)
df

      name gender  grade major score  study hour
0  timothy      m      1    ee     a           6
1    james      f      2    ee     c           7
2   thomas      m      3    ee     b           2
3     paul      f      4    cs     f           3
4    pedro      m      1    cs     a           4
5    maria      f      2    ds     b           5
6     john      m      3    ee     b           2
7   joseph      m      4    cs     c           6
8    David      f      1    ds     c           7
9     leon      m      2    ee     c          12

In [3]:
df.to_csv("students.csv", index=False) #csv 로 저장
df = pd.read_csv("students.csv") #csv 불러옴
df.head()

      name gender  grade major score  study hour
0  timothy      m      1    ee     a           6
1    james      f      2    ee     c           7
2   thomas      m      3    ee     b           2
3     paul      f      4    cs     f           3
4    pedro      m      1    cs     a           4

In [4]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     object
 1   gender      10 non-null     object
 2   grade       10 non-null     int64
 3   major       10 non-null     object
 4   score       10 non-null     object
 5   study hour  10 non-null     int64
dtypes: int64(2), object(4)
memory usage: 612.0+ bytes

           grade  study hour
count  10.000000   10.000000
mean    2.300000    5.400000
std     1.159502    2.988868
min     1.000000    2.000000
25%     1.250000    3.250000
50%     2.000000    5.500000
75%     3.000000    6.750000
max     4.000000   12.000000

## 데이터 구조 확인

이 데이터는 학생들의 성별, 학년, 전공, 점수, 공부 시간, 합격 여부를 포함한다.
오늘은 범주형 컬럼을 기준으로 데이터를 집계하는 연습을 한다.

In [27]:

df["grade"].value_counts() #value_counts = 범주별 개수 세기

grade
1    4
2    4
3    4
4    3
Name: count, dtype: int64

In [7]:
df.groupby("gender")["study hour"].mean() #gender 기준으로 나누고, 공부시간의 평균을 구한다.

gender
f    5.500000
m    5.333333
Name: study hour, dtype: float64

In [11]:
df.groupby("grade")["study hour"].agg(["count", "mean", "max", "min"])
#agg 로 한번에 보기

       count      mean  max  min
grade
1          3  5.666667    7    4
2          3  8.000000   12    5
3          2  2.000000    2    2
4          2  4.500000    6    3

In [12]:
df.sort_values(by="study hour", ascending=False) #값 기준으로 정렬

      name gender  grade major score  study hour
9     leon      m      2    ee     c          12
1    james      f      2    ee     c           7
8    David      f      1    ds     c           7
0  timothy      m      1    ee     a           6
7   joseph      m      4    cs     c           6
5    maria      f      2    ds     b           5
4    pedro      m      1    cs     a           4
3     paul      f      4    cs     f           3
2   thomas      m      3    ee     b           2
6     john      m      3    ee     b           2

In [14]:
gender_study = df.groupby("gender")["study hour"].mean()
gender_study.sort_values(ascending=False) #성별 평균 공부시간 구하고, 높은 순서로 정렬

gender
f    5.500000
m    5.333333
Name: study hour, dtype: float64

문제 풀기

In [15]:
import pandas as pd
data = {
    "name": ["Jisoo", "Minho", "Yuna", "David", "Sara", "Tom", "Hana", "John", "Mina", "Chris",
             "Nari", "Leo", "Sumin", "Kevin", "Jane"],
    "gender": ["F", "M", "F", "M", "F", "M", "F", "M", "F", "M",
               "F", "M", "F", "M", "F"],
    "grade": [1, 2, 3, 1, 2, 3, 1, 4, 4, 2,
              3, 4, 2, 1, 3],
    "major": ["EE", "CS", "DS", "EE", "CS", "DS", "EE", "CS", "DS", "EE",
              "CS", "DS", "EE", "CS", "DS"],
    "score": [82, 75, 91, 68, 88, 79, 95, 84, 90, 72,
              86, 77, 93, 65, 89],
    "study_hours": [5, 3, 6, 2, 5, 4, 7, 4, 6, 3,
                    5, 4, 7, 2, 6],
    "pass": ["Pass", "Pass", "Pass", "Fail", "Pass", "Pass", "Pass", "Pass", "Pass", "Pass",
             "Pass", "Pass", "Pass", "Fail", "Pass"]
}

df = pd.DataFrame(data)
df

     name gender  grade major  score  study_hours  pass
0   Jisoo      F      1    EE     82            5  Pass
1   Minho      M      2    CS     75            3  Pass
2    Yuna      F      3    DS     91            6  Pass
3   David      M      1    EE     68            2  Fail
4    Sara      F      2    CS     88            5  Pass
5     Tom      M      3    DS     79            4  Pass
6    Hana      F      1    EE     95            7  Pass
7    John      M      4    CS     84            4  Pass
8    Mina      F      4    DS     90            6  Pass
9   Chris      M      2    EE     72            3  Pass
10   Nari      F      3    CS     86            5  Pass
11    Leo      M      4    DS     77            4  Pass
12  Sumin      F      2    EE     93            7  Pass
13  Kevin      M      1    CS     65            2  Fail
14   Jane      F      3    DS     89            6  Pass

In [16]:
df["gender"].value_counts()

gender
F    8
M    7
Name: count, dtype: int64

In [17]:
df["major"].value_counts()

major
EE    5
CS    5
DS    5
Name: count, dtype: int64

In [18]:
df.groupby("gender")["score"].mean()

gender
F    89.250000
M    74.285714
Name: score, dtype: float64

In [19]:
df.groupby("major")["score"].mean()

major
CS    79.6
DS    85.2
EE    82.0
Name: score, dtype: float64

In [20]:
df.groupby("major")["score"].agg(["mean", "max", "min"])

       mean  max  min
major
CS     79.6   88   65
DS     85.2   91   77
EE     82.0   95   68

In [21]:
df.sort_values(by="score", ascending=False)

     name gender  grade major  score  study_hours  pass
6    Hana      F      1    EE     95            7  Pass
12  Sumin      F      2    EE     93            7  Pass
2    Yuna      F      3    DS     91            6  Pass
8    Mina      F      4    DS     90            6  Pass
14   Jane      F      3    DS     89            6  Pass
4    Sara      F      2    CS     88            5  Pass
10   Nari      F      3    CS     86            5  Pass
7    John      M      4    CS     84            4  Pass
0   Jisoo      F      1    EE     82            5  Pass
5     Tom      M      3    DS     79            4  Pass
11    Leo      M      4    DS     77            4  Pass
1   Minho      M      2    CS     75            3  Pass
9   Chris      M      2    EE     72            3  Pass
3   David      M      1    EE     68            2  Fail
13  Kevin      M      1    CS     65            2  Fail

In [23]:
avg = df.groupby("major")["score"].mean()
avg.sort_values(ascending=False)

major
DS    85.2
EE    82.0
CS    79.6
Name: score, dtype: float64

In [26]:
pass_df = df[df["pass"] == "Pass"] #pass 한 학생들 평균 점수
pass_df.groupby("major")["score"].mean()

major
CS    83.25
DS    85.20
EE    85.50
Name: score, dtype: float64

In [28]:
over = df[df["score"] >= 80]
over["grade"].value_counts() #점수가 80점 이상인 학생들만 골라서 학년별 학생 수를 구해라.

grade
3    3
1    2
2    2
4    2
Name: count, dtype: int64

In [29]:
df.groupby("major")[["study_hours", "score"]].mean()

       study_hours  score
major
CS             3.8   79.6
DS             5.2   85.2
EE             4.8   82.0

# Day 5 정리

## 오늘 배운 것

- value_counts()는 범주별 개수를 셀 때 사용한다.
- groupby()는 특정 컬럼을 기준으로 데이터를 묶어서 평균, 합계, 개수 등을 계산할 때 사용한다.
- sort_values()는 값을 기준으로 데이터를 정렬할 때 사용한다.
- groupby와 sort_values를 함께 쓰면 범주별 평균이 높은 순서대로 볼 수 있다.